40324 - Create ETS import tool
contactless/wb-mqtt-knx pull request #15
Opened 2021-12-09 15:10 UTC by rkochkin

* Implemented ETS importer
* Added tests and documentation
* Added 2-level and freeLevel ETS export parser
* Added ETS config tool tests
* Added description of the ETS import tool

2021-12-09 15:50 UTC, KraPete requested changes

2021-12-09 15:50 UTC, KraPete commented on etsconfigtool/src/etsconfigtool.cpp
> +                     "tinyxml2::LoadFile() error= XMLError::" + std::to_string(static_cast<int32_t>(result)));
А нет какой-нибудь функции, которая это в человекочитаемую строку превращает?

2021-12-09 15:50 UTC, KraPete commented on etsconfigtool/src/etsconfigtool.cpp
> +        wb_throw(TKnxException, "ETS export RootElement is corrupt");
1. corrupted
2. Реально LoadFile может завершиться успехом и вернуть nullptr тут?

2021-12-09 15:50 UTC, KraPete commented on etsconfigtool/test/ut_etsconfigtool.cpp
> +    converter.SaveWbMqttConfig(TempConfigFilePath);
Можно возвращать Json::Value, а писать в файл отдельной функцией. Тогда не надо временных файлов и кода тут меньше будет.

2021-12-09 15:50 UTC, KraPete commented on etsconfigtool/src/etsconfigtool.cpp
> +        static const std::unordered_map<uint32_t, std::string> generalTypeMap = {{1, "1.xxx_B1"},
Может это файликом сделать, чтоб не перекомпилять каждый раз?

2021-12-09 15:50 UTC, KraPete commented on etsconfigtool/src/mqttknxconfig.cpp
> +    RootObject = Json::Value(Json::objectValue);
Можно просто `Json::Value RootObject;`

2021-12-09 15:50 UTC, KraPete commented on etsconfigtool/test/ut_etsconfigtool.cpp
> +#include "config.h"
Ты нигде не проверяшь, что содержимое файла соответствует исходному xml. Структура верная, но там могут быть не те значения и т.п.

2021-12-14 07:14 UTC, rkochkin commented on etsconfigtool/src/etsconfigtool.cpp
> +                     "tinyxml2::LoadFile() error= XMLError::" + std::to_string(static_cast<int32_t>(result)));
Да, есть. Поправил.

2021-12-14 07:14 UTC, rkochkin commented on etsconfigtool/src/etsconfigtool.cpp
> +        wb_throw(TKnxException, "ETS export RootElement is corrupt");
1. Поправил
2. Да. Проверил специально.

2021-12-14 07:15 UTC, rkochkin commented on etsconfigtool/src/mqttknxconfig.cpp
> +    RootObject = Json::Value(Json::objectValue);
Поправил

2021-12-14 08:45 UTC, rkochkin commented on etsconfigtool/test/ut_etsconfigtool.cpp
> +    converter.SaveWbMqttConfig(TempConfigFilePath);
В утилите Json::Value снаружи класса нигде не используется. 
Сделал по другому. Добавил в класс метод валидации по схеме. Теперь создаю временный файл только в одном тесте: проверка корректности записи файла.

2021-12-14 09:17 UTC, rkochkin commented on etsconfigtool/src/etsconfigtool.cpp
> +        static const std::unordered_map<uint32_t, std::string> generalTypeMap = {{1, "1.xxx_B1"},
При добавлении новых типов, всё равно нужно будет перекомпилить wb-mqtt-knx.
Думаю тут нужно ввести общую для импортера и wb-mqtt-knx структуру или класс, в которой типы датапоинтов будут представляться числами: НомерГлавнойГруппы.НомерПодгруппы, и можно будет конвертировать их в строку.

Планирую сделать это в задаче:
https://wirenboard.bitrix24.ru/company/personal/user/204/tasks/task/view/43096/

2021-12-14 12:06 UTC, rkochkin commented on etsconfigtool/test/ut_etsconfigtool.cpp
> +#include "config.h"
Добавил тест

2021-12-20 11:06 UTC, webconn approved these changes
Думаю, надо вливать, можно только вот это поправить

2021-12-20 11:06 UTC, webconn commented on etsconfigtool/src/main.cpp
> +    }
`return 0` в конце нет (и странно, что у нас компилятор на это не ругается)

2021-12-24 07:46 UTC, rkochkin commented
Изменения этого PR влили в мастер с  кумулятивным PR: https://github.com/wirenboard/wb-mqtt-knx/pull/18

2021-12-24 07:46 UTC, closed without merging