41302 Add poll to read group objects
contactless/wb-mqtt-knx pull request #16
Opened 2021-12-14 06:05 UTC by rkochkin

* Добавлен периодический запрос чтения групповых объектов KNX устройств.
* Добавлен таймаут опроса. Если время ожидания ответа превышено, в топик `/meta/error` для соответствующего контрола публикуется ошибка.
* Добавлена отправка запросов на чтение для всех устройств при старте.

2021-12-20 11:39 UTC, webconn requested changes

2021-12-20 11:39 UTC, webconn commented on wb-mqtt-knx.schema.json
> +        "readPoolTimeout": {
`poll`, опечатка, причём везде расползлась

2021-12-20 11:39 UTC, webconn commented on src/ticktimer.cpp
> +    Worker = WBMQTT::MakeThread("KnxClient thread", {[this] { Processing(); }});
Назвал бы его `TimerThread`. Эти имена видны в дереве процессов, при отладке бывает очень удобно

2021-12-21 10:08 UTC, rkochkin commented on wb-mqtt-knx.schema.json
> +        "readPoolTimeout": {
Поправил

2021-12-21 10:09 UTC, rkochkin commented on src/ticktimer.cpp
> +    Worker = WBMQTT::MakeThread("KnxClient thread", {[this] { Processing(); }});
Переименовал

2021-12-22 12:21 UTC, webconn approved these changes

2021-12-24 07:45 UTC, rkochkin commented
Изменения этого PR влили в мастер с  кумулятивным PR: https://github.com/wirenboard/wb-mqtt-knx/pull/18

2021-12-24 07:45 UTC, closed without merging