Feature/45360 add date time scene dpts
contactless/wb-mqtt-knx pull request #22
Opened 2022-02-01 13:03 UTC by rkochkin

Добавил 4 новых типа датапоинтов, описание и тесты.

2022-02-07 08:01 UTC, webconn requested changes

2022-02-07 08:01 UTC, webconn commented on src/knxgroupobject/dpt10.cpp
> +    return {{"Day", "value", 0, 7}, {"Hour", "value", 0, 23}, {"Minutes", "value", 0, 59}, {"Seconds", "value", 0, 59}};
Мне кажется, тут было бы удобней выводить время в строке по ISO 8601, а то предвкушаю, как весело будет в скриптах собирать это всё по кусочкам. Для дня недели оставить отдельный контрол.

2022-02-07 08:01 UTC, webconn commented on src/knxgroupobject/dpt11.cpp
> +    return {{"Day", "value", 1, 31}, {"Month", "value", 1, 12}, {"Year", "value", 0, 99}};
Тут аналогично, предлагаю закодировать в строку по ISO 8601, "YYYY-MM-DD"

2022-02-07 08:01 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
Вот тут, кстати, будет какая-то хитрость. Я так понимаю, что это сообщение нужно отправлять в момент, когда надо либо запомнить сцену, либо проиграть (это и определяется первым полем). С этой точки зрения отправка сообщения при установке `SceneNumber` отдельно от состояния первого поля будет не просто некорректной, а ещё и заставит случайно проиграть или запомнить сцену.

Могу сходу представить такие способы решения (ни один не нравится на 100%):

 а) сделать вместо `switch` два `pushbutton` (`Learn` и `Activate`), на изменение `SceneNumber` не реагировать, отправлять сообщение при нажатии на `pushbutton`. Хорошо для управления, но не годится на приём;
 б) сделать один текстовый контрол с форматом в духе `learn X|activate X`, а то и JSON туда класть. Нормально на приём, не очень удобно для управления (кнопку-то из интерфейса нажать было бы удобней).
 
Не знаю, что лучше выбрать, можно у пользователя на форуме спросить, конечно

2022-02-07 08:05 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
Кстати, как вариант, можно было бы сделать два разных логических типа на это сообщение, один для отправки (роль sender) с pushbutton-ами, и один для получения (роль receiver) с текстовым полем `command` (значения learn/activate) и номером сцены.

Или объединить эти два варианта и представлять первое поле и как pushbutton, и как текст, тогда в роли `sender` скрипты на контроллере смогут корректно среагировать на отправку команды.

2022-02-08 10:32 UTC, rkochkin commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
Применяемая сейчас концепция для WB-MQTT работает с понятием контрол. 

Контрол - это независимая логическая переменная, не составного типа, к которой применяются 2 метода: чтение и запись. С логическим контролом прозрачно связано устройство. 
Каждая переменная может быть установлена отдельно, без взаимного влияния на остальные.

Концепция не предполагает работу с контролом как составным типом, например кортежем, который может быть записан или считан за одну единицу обмена.

В KNX, несмотря на некоторую свою примитивность, напротив, единицами обмена являются кортежи с элементами, имеющими элементарные типы.

Проблема отображения WB-MQTT в KNX сейчас не может иметь лаконичного решения. Все решения будут сводится к нескольким обобщённым вариантам:

* Использование контрола как буфера, хранящего временное значение - элемент кортежа. Когда буферы заполнены элементами кортежа, по определённому критерию происходит отправка значений из буферов в KNX одной посылкой. 
Это покрывает предположение Никиты: `сделать вместо switch два pushbutton (Learn и Activate), на изменение SceneNumber не реагировать`
На мой взгляд, унифицированным решением здесь является создание типового контрола `sync`, для соответствующего кортежа, отправка в который будет служить признаком для отправки кортежа из, предварительно заполненных значениями, буферов. При приёме пакета из KNX аналогично: сначала приходят сообщения из всех топиков, соответствующих элементам кортежа, затем присылается `sync`. 
Огромный минус здесь - зависимость от последовательности обмена.

* Перенос обработки кортежей за пределы ответственности WB-MQTT.  
Как пример: контрол представляется простым текстовым полем, в который в передаются/принимаются структурированные строки, содержащие все элементы кортежа в определённом формате.
Это покрывает предположение Никиты: `сделать один текстовый контрол с форматом в духе learn X|activate X`
Здесь мне кажется тоже можно унифицировать, например JSON строкой. 
Но у этого подхода минус - это ручная обработка данных, которую, по хорошему счёту, можно упростить, используя элементы WB-MQTT.

В данный момент, при изменении значения любого контрола, связанного с элементом кортежа для KNX датапоинта,  происходит отправка всего кортежа с остальными элементами кортежа, которые были записаны ранее.

Считаю что лучше сосредоточится на разработке и описании элементов кортежа датапоинтов, чем каждый раз придумывать уникальный костыль, для обхода невозможности одновременной отправки в KNX.

@webconn @evgeny-boger @KraPete @brainroot  Как вы считаете? 

Лично  склоняюсь к первому варианту как к компромиссному: Использовать `sync` для составных датапоинтов.
Это позволить использовать наработки WB-MQTT, и добавит особенность в виде необходимости отправлять `sync`.

2022-02-08 12:00 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
Расскажу про своё видение этой проблемы.

Нынешняя MQTT-конвенция изначально делалась из расчёта работы с относительно простыми устройствами/протоколами, в основном Modbus и всякими реле / датчиками / счётчиками. Составные контролы встречались (да и до сих пор встречаются) довольно редко, и в нашем случае их получалось разбивать на отдельные контролы. Проблемы с атомарными типами решали как могли по ситуации (кстати, таким типом является RGB).

Строго говоря, эта история с KNX пока держалась в концепции "редкого случая", тем более первая реализация wb-mqtt-knx оперировала телеграммами и там эта атомарность обеспечивалась на уровне системы ценой слабой интеграции в нашу инфраструктуру.

С топиком-стробом (твой `sync`) мы продлим время жизни нынешней конвенции ради того, чтобы сейчас не вводить никаких инфраструктурных изменений. И, вообще говоря, это так же повлияет на ощущение целостности нашей конвенции: везде можно писать в контрол и получать результат сразу, а тут вот нельзя, и узнать об этом можно, только взглянув на структуру топиков и увидев эту связь (или прописывать эту связь в /meta, что тоже нехорошо).

В общем, я тут скорее за то, чтобы сделать поддержку JSON как значений для подобных контролов (я сейчас не хочу называть их "составными", это слово у меня было в концептах новой конвенции и обозначает скорее логическое склеивание отдельных топиков). Пока это касается таких редко встречающихся ситуаций, мы можем даже сильно не заморачиваться с отображением в интерфейсе и описанием в `/meta` (если в `/meta` будет лежать JSON-схема, будет здорово и весело, @KraPete уже должен быть в восторге). Публиковать их можно нормально через что угодно, парсить при желании тоже, формат относительно компактный, и вообще много где применяется в сервисах на основе MQTT.

Если кто-то ещё хочет набросить тезисов, давайте соберём их здесь, все их почитают и потом обсудим вслух.

2022-02-08 12:05 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
а давайте вернёмся вот прямо к конкретной задаче. Что это за тип данных в KNX и как она работает?

2022-02-08 12:06 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
Насколько я понял из документации, это команда, которая говорит всем на шине либо "запомните своё состояние, это сцена номер N" либо "включите запомненное состояние из сцены N" в зависимости от первого бита пейлоада

2022-02-08 12:12 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
в чём проблема тогда сделать два контрола: один для запоминания, один для проигрывания?

В WB-MIR мы вообще это разбили на кучу pushbutton-ов, и так даже кажется удобнее.

2022-02-08 12:19 UTC, rkochkin commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
Другой пример, датапоинт Time:
Он состоит из 4 полей: день недели(1-7), час, минута, секунда. 
Из KNX такие датапоинты приходят за раз одним пакетом. Приходит просто массив байт в котором на определённых местах стоят значения. На каких местах, какой размерности значения и как их интерпретировать известно заранее и следует из типа датапоинта (Time, Date, ControlScene).

2022-02-08 12:21 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
этот датапоинт Time нам в какую сторону нужно передавать? Из шины к нам в интерфейс, из интерфейса в шину, и туда и туда? В каких случаях?

В общем я здесь сильно против какого-то допиливания конвенции под KNX-овую упаковку данных, потому что не понимаю, чем это отличается от сырых телеграм из knx/data.

2022-02-08 13:22 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> в чём проблема тогда сделать два контрола: один для запоминания, один для проигрывания?
Потому что помимо кнопки там будет ещё и контрол с номером сцены. В принципе, я считаю это неплохим вариантом, за исключением случаев, если кто-то захочет настроить реакцию WB на рассылку такого сообщения снаружи. Если выкинуть идею про получение этого сообщения снаружи, можно вообще RPC обойтись.

> этот датапоинт Time нам в какую сторону нужно передавать? Из шины к нам в интерфейс, из интерфейса в шину, и туда и туда? В каких случаях?
За этот датапоинт я переживаю меньше, пока не вижу серьёзных причин не бить его на отдельные контролы.

2022-02-08 13:26 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> В общем я здесь сильно против какого-то допиливания конвенции под KNX-овую упаковку данных, потому что не понимаю, чем это отличается от сырых телеграм из knx/data.

Кстати, может и не такая плохая идея разделить приём и передачу в таких случаях, и использовать RPC для отправки, чтобы не играть в странные игры с отображением. Правда, им у нас никто пользоваться не умеет

2022-02-08 13:32 UTC, KraPete commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
1. Для сцены я бы сделал в mqtt отдельный контрол под каждую сцену. Тогда это просто switch и всё. Правда, трансляция в knx будет немного сложнее чем просто перекодирование байтиков, надо будет учитывать название контрола и ассоциированные с ним данные в конфиге.
2. Time, да, надо понимать, в какую сторону мы пишем. Если knx -> mqtt проблем нет. mqtt -> knx надо ли вообще? Есть ли реальные задачи клиентов? Так что я бы сделал такой контрол readonly и не парился пока.

2022-02-08 13:34 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> 1. Для сцены я бы сделал в mqtt отдельный контрол под каждую сцену. Тогда это просто switch и всё. 

а) не switch, а два pushbutton
б) очень много кнопок получится, но в теории это правда решение, примерно как с MIR

2022-02-08 14:43 UTC, rkochkin commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> Для сцены я бы сделал в mqtt отдельный контрол под каждую сцену. Тогда это просто switch и всё.

Всего можно задать 64 сцены - это много контролов получится.

Датапоинты Time как читаются с KNX устройств, так и записываются на KNX устройства. 
Контроль сцены как принимается так и передаётся, если на шине присутствуют как задающее устройство, так и актуаторы.

Я бы вообще не смотрел на особенности каждого конкретного датапоинта: невозможно предугадать как он будет использован. В этой игре легко проиграть и потратить 80% времени, сделав 20% результата.

В текущей реализации wb-mqtt-knx правила просты: 
1. Каждому групповому адресу соответствует определённый тип датапоинта
2. Каждое поле в датапоинте  (из пейлоада KNX телеграммы) - это отдельный wb-mqtt контрол. 
3. Эти контролы связаны  одинаковым префиксом в ID и Title.
4. Если поле это бит, то контрол имеет тип "switch", если число, то контрол: "value".
5. При записи в любой связанный контрол, KNX телеграмма отправляется со значениями связанных контролов.

Если вводить промежуточный интерфейс, уникальный для каждого датапоинта, то это долго придумывать, трудно поддерживать, сложно понять пользователю.

2022-02-08 15:02 UTC, rkochkin commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> Если knx -> mqtt проблем нет. mqtt -> knx надо ли вообще? Есть ли реальные задачи клиентов? 

Существуют KNX таймеры в которые можно как писать так и читать. Думаю что это сделано для установки времени. Если нет внешнего интерфеса, то время по другому на устройстве не настроить.

У клиента с форума, был запрос на добавлние Date, Time, Scene, ControlScene. Поэтому был создан этот PR.
https://support.wirenboard.com/t/obnovlenie-dlya-knx-mqtt-servisa/9773/17

2022-02-08 17:21 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
>Я бы вообще не смотрел на особенности каждого конкретного датапоинта: невозможно предугадать как он будет использован. В этой игре легко проиграть и потратить 80% времени, сделав 20% результата.

Это всего лишь перевешивание работы на конечного интегратора, вот и всё. Проходили это уже с прозрачным мостом для телеграм, никто не осилил.

Давайте реализуем какой-то fallback-тип или канал, который правда позволит что угодно слать как JSON, чтобы у пользователей была возможность пользовать в том числе типами, которые мы не **пока** не поддержали нативно. 

>Всего можно задать 64 сцены - это много контролов получится.

мы так сделали в MIR и много жалоб не было. Если у клиента действительно используется 64 сцены, то ему действительно для работы в нашей системе будет удобнее иметь 64 pushbutton-а на их активацию.
Надо просто число делать настраиваемым и всё.

>Существуют KNX таймеры в которые можно как писать так и читать. Думаю что это сделано для установки времени. Если нет внешнего интерфеса, то время по другому на устройстве не настроить.

С временем я не вижу проблем в том, чтобы добавить тип данных "время" в нашу MQTT-конвенцию. Передавать, не знаю, как unix epoch, например, или как iso string. Это уже пару раз нужно было и в других местах.
Реализуется тривиально.

>В текущей реализации wb-mqtt-knx правила просты:

Всё-таки ценность в ПО - это не внутренняя красота, а решение пользовательских задач.

2022-02-08 17:28 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> С временем я не вижу проблем в том, чтобы добавить тип данных "время" в нашу MQTT-конвенцию. 

Я тоже за это, но тут KNX подкинул нам офигенное сообщение `Time`, где помимо времени лежит ещё день недели, в ISO такого нет. Вывести его как строку вида `Sun 12:34:56` почти ничего не мешает, но взаимозаменяемости не будет тогда.

> Давайте реализуем какой-то fallback-тип или канал, который правда позволит что угодно слать как JSON, чтобы у пользователей была возможность пользовать в том числе типами, которые мы не пока не поддержали нативно.

Если под "нативно" ты имеешь в виду не "в wb-mqtt-knx", а "на уровне конвенции", то лайк. В противном случае придётся либо прямо сейчас распарсить все типы телеграмм в JSON (что много работы), либо получится контрол как старый `knx/data`, но с новым форматом.

2022-02-08 18:58 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> либо получится контрол как старый knx/data, но с новым форматом

ну я вот про это. То есть чтобы не было задачи с KNX, которую у нас нельзя решить. Есть те, которые решить сложно.

Просто в старом knx/data были битики, а мы можем всё-таки телеграмму разобрать на составляющие куски теперь кажется.

2022-02-08 19:00 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
>Я тоже за это, но тут KNX подкинул нам офигенное сообщение Time, где помимо времени лежит ещё день

И кто как этим пользуется?

2022-02-08 19:01 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> Просто в старом knx/data были битики, а мы можем всё-таки телеграмму разобрать на составляющие куски теперь кажется

Так чтобы разбить телеграмму на куски (до конца), надо написать парсеры для всех типов. Ну или просто в JSON перепаковать те же битики, что и раньше

2022-02-09 01:59 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> Так чтобы разбить телеграмму на куски (до конца), надо написать парсеры для всех типов. Ну или просто в JSON перепаковать те же битики, что и раньше

так там же есть весьма конечная табличка, которая ещё и явно машиночитаемая где-нибудь бывает.

![image](https://user-images.githubusercontent.com/1755320/153107462-c3c66c65-ffbb-4555-80d0-c4c93722787a.png)
![image](https://user-images.githubusercontent.com/1755320/153107492-2ed4ddca-9938-4d15-b377-5e551d8492d7.png)

2022-02-09 02:16 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
т.е. я предлагаю взять и сделать для этого дататипа такое вот описание:
```
{
 "id" : "10.001",
  "name" : "DPT_TimeOfDay",
  "format" : "N3U5r2U6r2U6",
  "field_names" : ["Day", "Hour", "Minutes", "Seconds"]
}
```

по которому драйвер сможет туда-обратно конвертировать сообщения из `knx/более_лучшеая_data`  в формате
```
{
 "Day" : 0,
 "Hour" : 22,
 "Minutes" : 1,
 "Seconds" : 2
}
```

прямо готового документа с машинночитаемыми field names я за две минуты в гитхабе не нагуглил, но даже самим из пдфки скопировать - это работы часа на четыре, которую ещё и можно поручить кому-нибудь из коллег.

2022-02-10 12:33 UTC, rkochkin commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
Возвращаясь к PR хочу сделать так:
![Component 5 (1)](https://user-images.githubusercontent.com/12100943/153407127-77cc90d3-989b-4638-a1a2-eb3af355ff40.png)


* **Time** - в отличие от ISO 8601 в формат добавляется число D - которое может принимать значение `0...7`. `0` - означает noDay. Хоть это нестандартно, но это один контрол, отправляемый и считываемый за раз. Он легко парсится.

* **Date** - Тоже нестандартное YY вместо YYYY, потому что в KNX датапоите год может принимать значение только `0..99`.

* **Scene** - оставил самую простую и удобную для обработки форму. Просто `value`

* **Control Scene** - сделал два контрола. Если номер сцены записывается в контрол `Activate`  - то отправляется телеграмма с командой активации, если в `Learn` то отправляется команда на сохранение. При приёме из KNX такая форма тоже легко обрабатывается. Это самый простой подход, на мой взгляд.

2022-02-10 12:44 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
За Control scene - лайк. Не идеальное решение (кнопка сподручней обычно), но уже должно хорошо работать, и кнопку уже можно легко дорисовать в правилах при необходимости.

Date - точно надо сделать в ISO, никаких препятствий нет для этого. Сконвертировать YYYY в YY несложно.

Time - вот я бы тут подумал. Тоже хочется оставить получить совместимость с ISO, так что как минимум разделители надо сделать двоеточиями `:`, и отделить от дня недели пробелом или каким-нибудь ещё символом (отличным от двоеточия).

А вообще я бы спросил у юзеров, часто ли там используется день недели - может, мы пытаемся реализовать не особо нужную фичу там, где можно было бы всегда писать 0. Если так, то можно было бы сделать два способа интерпретации этого поля - с днём недели и без, для разных случаев, чтобы те, кому нужно только время, могли не привязываться к особому формату.

2022-02-10 14:06 UTC, rkochkin commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> Date - точно надо сделать в ISO, никаких препятствий нет для этого. Сконвертировать YYYY в YY несложно.

YYYY -> YY не сложно, сложно обратное YY -> YYYY. Не хочется добавлять информацию, которой просто нет в KNX телеграмме. Либо заполнять нулями первые две позиции в YYYY.

> Time - вот я бы тут подумал. Тоже хочется оставить получить совместимость с ISO

Может так?  `HH:MM:SS D`
Можно сделать, что если в контрол записывается дата в формате `HH:MM:SS`, то день недели выставляется по умолчанию `D := noDay`. Аналогично при приёме, если в телеграме `D := 0`, то мы выводим в контроле `HH:MM:SS`

2022-02-10 14:15 UTC, webconn commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> YYYY -> YY не сложно, сложно обратное YY -> YYYY. Не хочется добавлять информацию, которой просто нет в KNX телеграмме. Либо заполнять нулями первые две позиции в YYYY.

Если уходить в формализм, то тут ты скорее прав. С другой стороны, не хочется из-за этого ограничения плодить разные форматы дат и портить взаимозаменяемость топиков. В крайнем случае значение префикса можно было бы в конфиге передать.

> Может так? `HH:MM:SS D` Можно сделать, что если в контрол записывается дата в формате `HH:MM:SS`, то день недели выставляется по умолчанию `D := noDay`. Аналогично при приёме, если в телеграме `D := 0`, то мы выводим в контроле `HH:MM:SS`

Да, формат мне нравится, но не думаю, что хорошей идеей будет добавлять D в конце, который будет то появляться, то нет, это неудобно парсить. Я тут скорее за то, чтобы сделать две реализации этого типа (time-only и time+dow), чтобы тем, кому не нужен день недели, не пришлось подкостыливать лишние данные.

2022-02-11 06:16 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
>Control Scene

как вызывать из правил одну сцену два раза подряд?

2022-02-11 06:20 UTC, evgeny-boger commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
>Time - в отличие от ISO 8601 в формат добавляется число D

я последовательно против того, чтобы создавать по новому формату топика под каждый безумный формат телеграмы, который мы встретим в каждом безумном протоколе.

Я бы сделал два контрола: с time и с dow. Под оба сделать типы в конвенциях. Да, это будет не атомарно на запись, и внимательный клиент сможет заметить, как на доли секунд на его панельке меняется день недели не одновременно со временем. Уверен, что всем пофиг.

2022-02-11 06:45 UTC, rkochkin commented on src/knxgroupobject/dpt18.cpp
> +    return {{"Control", "switch", 0, 1}, {"SceneNumber", "value", 1, 64}};
> Если уходить в формализм, то тут ты скорее прав. С другой стороны, не хочется из-за этого ограничения плодить разные форматы дат и портить взаимозаменяемость топиков. В крайнем случае значение префикса можно было бы в конфиге передать.

Тогда делаю YYYY и первые две позиции заполню нулями. Это решение позволит расширить функциональность в будущем, не меняя формат.

> Да, формат мне нравится, но не думаю, что хорошей идеей будет добавлять D в конце, который будет то появляться, то нет, это неудобно парсить. Я тут скорее за то, чтобы сделать две реализации этого типа (time-only и time+dow), чтобы тем, кому не нужен день недели, не пришлось подкостыливать лишние данные.

Пока хочу сделать базовый `HH:MM:SS D`, в котором содержится полная информация. 
Затем в будущем можно будет добавить тип с `HH:MM:SS`.

2022-11-22 11:13 UTC, rkochkin commented
Задача заморожена.
https://wirenboard.bitrix24.ru/workgroups/group/218/tasks/task/view/45360/

2022-11-22 11:13 UTC, closed without merging