Feature/48210 add support for json types to ets import tool
contactless/wb-mqtt-knx pull request #27
Opened 2022-06-16 21:53 UTC by rkochkin

Для утилиты экспорта из ETS добавлена поддержка JSON типов. 
Если для Id датапоинта из ETS экспорта нет соответствующего wb-mqtt типа, то выбирается JSON тип. Если и его нет, выбирается дефолтный тип.

2022-06-17 04:37 UTC, KraPete requested changes

2022-06-17 04:37 UTC, KraPete commented on src/knxgroupobject/datapointid.cpp
> +            } else if (HasSub == rhs.HasSub) {
У тебя ж тут везде return. Зачем else?

2022-06-17 04:37 UTC, KraPete commented on src/knxgroupobject/datapointid.cpp
> +                        return true;
Можно в одно условие переписать, будет понятнее

2022-06-17 06:18 UTC, rkochkin commented on src/knxgroupobject/datapointid.cpp
> +            } else if (HasSub == rhs.HasSub) {
Поправил

2022-06-17 06:18 UTC, rkochkin commented on src/knxgroupobject/datapointid.cpp
> +                        return true;
Переписал в одно условие

2022-06-20 13:36 UTC, webconn requested changes

2022-06-20 13:36 UTC, webconn commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<PDpt> Create(const TDatapointId& datapointId) = 0;
Казалось бы, прелесть указателей в том, что они nullable сами по себе, надо ли для этого ещё optional вводить?

2022-06-20 13:36 UTC, webconn commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<std::string> GetDptConfigName(
Кажется, что этот метод нарушает тут принцип единственной ответственности (почему бы не вытащить это имя из уже полученного DPT?)

2022-06-20 13:36 UTC, webconn commented on src/knxgroupobject/idptbuilder.h
> +            virtual bool HasDpt(const TDatapointId& datapointId) const = 0;
Этот метод снаружи нигде не используется, можно было бы и не вытаскивать

2022-06-22 08:40 UTC, rkochkin commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<std::string> GetDptConfigName(
Не хотелось бы создавать объект, только с целью увидеть как записано его имя в файле конфигурации.
По хорошему нужно вообще вынести работу с конфигом в отдельный интерфейс из idptbuilder.

2022-06-22 09:19 UTC, webconn commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<std::string> GetDptConfigName(
Ну вроде как мы эти объекты класса `IDpt` таким образом переиспользуем. Кода становится меньше от этого. Производительностью не жертвуем, потому что выполняться это будет один раз при импорте. Плюс, не имеем одновременно две реализации получения имени (одна для `Create`, вторая для `GetDptConfigName`). Я бы сейчас объединил

2022-06-22 11:52 UTC, rkochkin commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<std::string> GetDptConfigName(
Кода не станет меньше от этого, он переедет в метод Create(), что нехорошо.
Для утилиты экспорта нужно всего лишь получать имена в конфиге. Для wb-mqtt-knx нужен вызов только Create().

2022-06-22 11:56 UTC, rkochkin commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<std::string> GetDptConfigName(
IDpt хранит в себе лишь правила обработки пакетов. Это его ответственность.
У обработчика конфига другая ответственность.

2022-06-23 12:31 UTC, rkochkin commented on src/knxgroupobject/idptbuilder.h
> +            virtual bool HasDpt(const TDatapointId& datapointId) const = 0;
Убрал

2022-06-23 12:37 UTC, rkochkin commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<std::string> GetDptConfigName(
Переделал.
Разделил ответственность. Теперь Builder только создаёт объекты IDpt, а Config только преобразует Id в человекочитаемую строку для конфига.
Получилось убрать зависимость утилиты ETS импортера от Builder mqtt типов и всех mqtt Dpt.

2022-06-23 13:02 UTC, rkochkin commented on src/knxgroupobject/idptbuilder.h
> +            virtual std::experimental::optional<PDpt> Create(const TDatapointId& datapointId) = 0;
Убрал

2022-06-23 14:07 UTC, webconn commented on src/knxgroupobject/basedptconfig.h
> +            virtual const std::map<TDatapointId, std::string>& GetConfigNameMap() const = 0;
Напрашивается typedef на этот тип

2022-06-23 14:07 UTC, webconn commented on src/knxgroupobject/idptbuilder.h
> +#include <experimental/optional>
Лишний optional

2022-06-23 14:07 UTC, webconn commented on test/ut_dptwbmqttconfig.cpp
> +    ASSERT_TRUE(name);
Тут же не `bool` выходит, может, лучше с пустой строкой сравнить для читаемости?

2022-06-23 14:07 UTC, webconn commented on test/ut_dptwbmqttconfig.cpp
> +    EXPECT_FALSE(name);
Тут тоже кажется, что лучше с пустой строкой сравнивать

2022-06-23 14:07 UTC, webconn commented on test/ut_dptjsonconfig.cpp
> +    ASSERT_TRUE(name);
И тут и ниже тоже вопрос про сравнение со строкой

2022-06-23 14:37 UTC, rkochkin commented on test/ut_dptwbmqttconfig.cpp
> +    ASSERT_TRUE(name);
Выходит optional который кастуется в bool. 
Пустая строка это особенность, которую нужно запоминать и где-то описывать. Мне кажется гораздо проще запоминается отсутствие результата (false), чем наличие результата который нужно сравнивать с особенной строкой вида "<пусто>".

2022-06-23 14:38 UTC, webconn commented on test/ut_dptwbmqttconfig.cpp
> +    ASSERT_TRUE(name);
Ага, сообразил

2022-06-23 15:02 UTC, rkochkin commented on src/knxgroupobject/basedptconfig.h
> +            virtual const std::map<TDatapointId, std::string>& GetConfigNameMap() const = 0;
Сделал alias

2022-06-23 15:03 UTC, rkochkin commented on src/knxgroupobject/idptbuilder.h
> +#include <experimental/optional>
Убрал

2022-06-23 15:15 UTC, webconn approved these changes

2022-06-24 10:05 UTC, merged