Feature/fixed debug logs
contactless/wb-mqtt-knx pull request #33
Opened 2022-09-02 17:20 UTC by rkochkin

* Поправил уровень логов для отладочного вывода.
* Создал класс индивидуальных адресов для преобразований.
* Сделал удобочитаемый отладочный вывод в лог приёма и отправки телеграмм. Индивидуальные и групповые адреса отображаются как i.i.i g/g/g соответственно.
* Сделал рефакторинг функций преобразования knx<->mqtt: уменьшил дублирование кода и упростил немного.

2022-09-08 13:09 UTC, KraPete approved these changes

2022-09-08 13:15 UTC, webconn requested changes

2022-09-08 13:15 UTC, webconn commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Скользкая дорожка, я считаю. На что оно ругалось?

2022-09-08 13:15 UTC, webconn commented on src/knxclientservice.cpp
> +    std::string ToLog(const knx::TTelegram& telegram, bool toSend)
Некрасиво класть bool, приходится лезть в определение функции, чтобы понять, что за `true` в аргументах. Лучше через enum флаги сделать.

2022-09-08 13:49 UTC, KraPete commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Дак это предупреждение, что в следующей версии `gcc` тут сломано ABI. Так что это безопасно

2022-09-08 13:50 UTC, KraPete commented on src/knxclientservice.cpp
> +    std::string ToLog(const knx::TTelegram& telegram, bool toSend)
Ты придираешься, но, конечно, прав. Я себя тоже часто ловлю на том, что надо делать `enum`, но в лом :)

2022-09-08 13:51 UTC, webconn commented on src/knxclientservice.cpp
> +    std::string ToLog(const knx::TTelegram& telegram, bool toSend)
Охотно верю :)

2022-09-08 13:56 UTC, webconn commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Ну такое, я не был бы уверен, что безопасно. Если прям уверены, что в определённом месте это ок, то лучше это место в `pragma` завернуть, а так мы затыкаем GCC на веки вечные по любому похожему поводу

2022-09-08 16:39 UTC, KraPete commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Собирать куски программы на С++ разными версиями `gcc` - идея для экстремалов. Я с ними не хочу. Так что, думаю, безопасно.

2022-09-09 04:52 UTC, rkochkin commented on src/knxclientservice.cpp
> +    std::string ToLog(const knx::TTelegram& telegram, bool toSend)
Добавил enum

2022-09-09 04:57 UTC, rkochkin commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
https://gcc.gnu.org/gcc-7/changes.html

> On ARM targets (arm*-*-*), [a bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=77728) introduced in GCC 5 that affects conformance to the procedure call standard (AAPCS) has been fixed. The bug affects some C++ code where class objects are passed by value to functions and could result in incorrect or inconsistent code being generated. This is an ABI change. If the option -Wpsabi is enabled (on by default) the compiler will emit a diagnostic note for code that might be affected.

Выдаётся куча бесполезных предупреждений. За этим лесом можно упустить что-то важное. 
pragma - плохой вариант. Если вдруг надо будет включить эти предупреждения для всего, то необходимо лезть в каждый файл где установлена  pragma.

2022-09-09 08:45 UTC, webconn commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
> Собирать куски программы на С++ разными версиями `gcc` - идея для экстремалов. Я с ними не хочу. Так что, думаю, безопасно.

У нас есть libwbmqtt1, который _теоретически_ может быть собран другой версией GCC. Если этот баг не аффектит работу с либой - не страшно.

> Выдаётся куча бесполезных предупреждений. За этим лесом можно упустить что-то важное.

Я понимаю, что GCC выдаёт кучу бесполезных предупреждений по поводу и без, но не просто же так включают `-Wall -Werror`. В моём представлении однажды кто-то серьёзно сломает что-то в ABI, а мы этого не узнаем, потому что на весь код стоит этот флаг. Можно сказать, что это вина разработчиков GCC, конечно, потому что они сами рекомендуют этот флаг ставить и тем самым себе же наступают на ноги, но с проблемами разбираться потом нам.

У нас много мест, на которые это предупреждение выводится? Если немного и они не вылезают наружу, я бы лучше код переделал. Если вылезают наружу - то вообще нельзя гасить предупреждения.

2022-09-09 09:27 UTC, rkochkin commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Я не думаю, что ради "diagnostic note" нужно переделывать корректный код, который использует RVO оптимизацию, чтобы обходить баг, которого нет. Это не предупреждение, что с кодом что-то не так, а предупреждение, что в этом месте могут возникнуть проблемы с совместимостью со старым GCC5 из-за бага.
@webconn тогда уберу -Wno-psabi, чтобы всегда было напоминание?

2022-09-09 09:33 UTC, webconn commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Я так и не понял, можно ли локализовать места, где это предупреждение возникает, и дописать туда `#pragma`? И есть ли места, которые касаются библиотек? Понимаю, что решение получается не очень красивое, но что поделать, если в GCC не придумали ничего лучше.

2022-09-09 10:05 UTC, KraPete commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
@webconn Эта штука не ловит автоматом изменения в ABI. Просто проверяет, что используется код, который промаркирован как изменяющийся. Т.е. разработчик должен руками задать места, где будет сломан ABI. И да, надо бы как-то проверять, что libwbmqtt1 собрана не совместимым компилятором.
Если я правильно помню, оно ругается на что-то из stdlib, так что выставить `#pragma` будет не тривиально. 
@rkochkin Посмотришь?

2022-09-09 10:07 UTC, rkochkin commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Можно, но зачем, если хочется, чтобы диагностические сообщения компилятора были на виду? 
Если возникнет важное предупреждение с файлом, где стоит #pragma, как их все оперативно отключить?
У меня diagnostic note возникает в каждом датапоинте, это с десяток классов.

Делать 

> #pragma GCC diagnostic push
> #pragma GCC diagnostic ignored "-Wno-psabi"
> void foo()
> {
> }
> #pragma GCC diagnostic pop

вокруг каждого метода, где используется возврат значения - мне кажется бессмысленно и вредно.
Проще оценить вероятность использования библиотек скомпилированных под GCC5(и, возможно, перекомпилить их), и оставить diagnostic note.
К тому-же гашение предупреждения никак не влияет на вероятность появления несовместимости.

2022-09-09 10:24 UTC, rkochkin commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
/usr/include/c++/10/bits/stl_vector.h: In constructor 'std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = knx::object::DptDescriptorField; _Alloc = std::allocator<knx::object::DptDescriptorField>]':
/usr/include/c++/10/bits/stl_vector.h:625:7: note: parameter passing for argument of type 'std::initializer_list<knx::object::DptDescriptorField>' changed in GCC 7.1
  625 |       vector(initializer_list<value_type> __l,
      |       ^~~~~~

2022-09-12 13:54 UTC, webconn commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
На планёрке решили оставить эти notes, не добавлять флагов, которые выключают сообщения

2022-09-12 14:13 UTC, rkochkin commented on CMakeLists.txt
> +add_compile_options(-Wall -Werror -pedantic -Wno-psabi)
Убрал  -Wno-psabi

2022-09-12 14:15 UTC, webconn approved these changes

2022-09-12 14:45 UTC, merged