54016 long service stop
contactless/wb-mqtt-knx pull request #34
Opened 2022-10-27 06:55 UTC by rkochkin

Вынес процесс соединения с knxd в основной поток.
Убрал задержку после получения сигналов от systemd во время старта и инициализации wb-mqtt-knx.

2022-10-27 17:32 UTC, sikmir commented
Можешь заодно поправить ошибку сборки с gcc 11:
```sh
wb-mqtt-knx> [ 29%] Building CXX object CMakeFiles/wb-mqtt-knx.dir/src/knxgroupobject/dptjsonfield.cpp.o
wb-mqtt-knx> /build/source/src/knxgroupobject/dptjsonfield.cpp: In member function 'void knx::object::TDptJsonField::SetValue(knx::object::TJsonFieldRawValue)':
wb-mqtt-knx> /build/source/src/knxgroupobject/dptjsonfield.cpp:66:82: error: call of overloaded 'Value(long long unsigned int)' is ambiguous
wb-mqtt-knx>    66 |                     Value = Json::Value(value.to_ullong() & ((1 << BitWidth) - 1));
wb-mqtt-knx>       |
```

Например так:
```diff
--- i/src/knxgroupobject/dptjsonfield.cpp
+++ w/src/knxgroupobject/dptjsonfield.cpp
@@ -63,7 +63,7 @@ namespace knx
                     break;
                 case EFieldType::UNSIGNED_INT:
                 case EFieldType::ENUM:
-                    Value = Json::Value(value.to_ullong() & ((1 << BitWidth) - 1));
+                    Value = Json::Value(static_cast<int64_t>(value.to_ullong() & ((1 << BitWidth) - 1)));
                     break;
                 case EFieldType::INT:
                     if (BitWidth == 8) {
```

2022-10-27 17:46 UTC, sikmir approved these changes

2022-10-28 10:34 UTC, KraPete commented
Можешь написать, как это ускорило завершение?

2022-11-01 06:22 UTC, webconn requested changes

2022-11-01 06:22 UTC, webconn commented on debian/changelog
> +  * Reduce service downtime
Это не `downtime`, `downtime` - это время, когда сервис недоступен, и к нашей ситуации не относится

2022-11-01 06:22 UTC, webconn commented on debian/wb-mqtt-knx.service
>  ExecStart=/usr/bin/wb-mqtt-knx
Есть смысл тут сразу подкрутить, чтобы было по гайдлайну: https://github.com/wirenboard/codestyle/blob/master/guidelines/services.md

2022-11-07 05:05 UTC, KraPete approved these changes

2022-11-07 05:05 UTC, KraPete commented on src/knxclientservice.cpp
> +    constexpr auto CONNECTION_THREAD_TIMEOUT = std::chrono::seconds(6);
Может, упомянуть как-то, что это таймаут на отключение от сервиса? Сейчас кажется, что это таймаут подключения.

2022-11-09 06:46 UTC, rkochkin commented on src/knxclientservice.cpp
> +    constexpr auto CONNECTION_THREAD_TIMEOUT = std::chrono::seconds(6);
Поправил

2022-11-09 07:12 UTC, rkochkin commented
Проблема с длительной остановкой сервиса заключается в том, что мы маскируем прерывания в начале выполнения сервиса. Затем запускается процесс соединения с knxd и открытия группового соединения EIBOpen_GroupSocket(). В этой функции поток висит достаточно долго, если у нас нет питания на knx модуле. Если в этот момент сервис остановить, следовательно послать сигнал SIGTERM, поток повисает в библиотечной функции EIBOpen_GroupSocket(). При попытке остановить сервис мы пытаемся присоединить этот поток, и сервис блокируется.
Сейчас для решения этой проблемы сделан фьючерс который ожидает остановки потока или таймаута.

2022-11-09 07:15 UTC, rkochkin commented on debian/wb-mqtt-knx.service
>  ExecStart=/usr/bin/wb-mqtt-knx
Сделал

2022-11-09 10:38 UTC, webconn approved these changes

2022-11-09 10:38 UTC, webconn commented on debian/wb-mqtt-knx.service
>  ExecStart=/usr/bin/wb-mqtt-knx
Почитал я внимательно исходники библиотеки, там, конечно, страх и ужас. Там библиотека вроде пытается делать асинхронные функции, но легче от этого не стало, проверка в случае GroupSocket всё равно блокирующая.

Я тут подумал, может, нам влить этот PR для ситуаций, когда что-то не так с модулем KNX, а здесь в файл сервиса дописать `ExecCondition`, который будет проверять, есть ли в контроллере модуль KNX, чтобы в случае чего не тратить время и память на запуск этого сервиса в принципе?

Возможно, это лучше даже сделать не здесь, а в wb-configs, добавив аналогичный `ExecCondition` в том числе и в knxd.

2022-11-09 10:39 UTC, webconn commented
Ещё допишу для истории, что переподключение к KNX выехало из внутренностей сервиса и перелегло на плечи systemd, мы об этом поговорили и решили, что в нынешнем состоянии сервиса так будет проще

2022-11-11 06:37 UTC, rkochkin commented on debian/wb-mqtt-knx.service
>  ExecStart=/usr/bin/wb-mqtt-knx
Поставил задачу для этого:
https://wirenboard.bitrix24.ru/company/personal/user/204/tasks/task/view/55062/

2022-11-11 06:38 UTC, merged