40324 Port wb-mqtt-knx to libwbmqtt1
contactless/wb-mqtt-knx pull request #5
Opened 2021-10-25 12:46 UTC by rkochkin

* Modified CmakeList.txt: Added compiler flags for debug profile and grouped test settings.
* Added cmake generated files and the IDE config files to .gitingnore
* Added .clang-format file to git ignore
* Port wb-mqtt-knx to libwbmqtt1

2021-10-25 12:52 UTC, webconn commented
Пока всё не смотрел, но сходу:
 * добавь Jenkinsfile, пример в wb-mqtt-serial (можно прям скопировать оттуда, должно заработать);
 * по-моему, тут будут несоответствия codestyle. У нас есть конфиг для clang-format и скрипт, который можно натравить для исправления: https://github.com/wirenboard/codestyle

2021-10-25 12:55 UTC, webconn commented
Если что, не обязательно закрывать PR каждый раз при предложении правок. Нормально, что здесь будут отображаться новые коммиты и продолжится дискуссия. Если наберётся много коммитов, ребейз можно сделать непосредственно перед мержем.

2021-10-26 07:01 UTC, KraPete requested changes
1. Надо комментарии к методам, не всегда ясно, что они делают, что им передавать, могут ли они выкидывать исключения, потокобезопасны ли они.
2. Меня уже тут били по рукам за `std::tuple`. Лучше возвращать структуру с нормальными менами полей.
3. Стоит посмотреть, где можно добавить к методам const.
4. Не понял, зачем сделаны интерфейсы `IKnxClient` и `IKnxService`?

2021-10-26 07:01 UTC, KraPete commented on debian/wb-mqtt-knx.init
>  #!/bin/sh
Зачем нам init? Мы ж на systemd пеехали

2021-10-26 07:01 UTC, KraPete commented on src/knxclientservice.cpp
> +    constexpr auto CLIENT_RECONNECT_PERIOD_S = 30;
Если константа в секундах, то используй `std::chrono::seconds`

2021-10-26 07:01 UTC, KraPete commented on src/knxclientservice.cpp
> +            if (res == -1)
Случаем нет констант на возвращаемые значения? Если нет, то, может, сделать свою для `-1`?

2021-10-26 07:01 UTC, KraPete commented on src/knxclientservice.cpp
> +        sleep(timeout);
Тут мы можем заснуть на 30 секунд, если кто-то решит остановить сервис, то он может пойти пить чай. Может, как-то это обойти?

2021-10-26 07:01 UTC, KraPete commented on src/knxconverter.cpp
> +std::string TKnxConverter::KnxTelegramToMqtt(const TTelegram& telegram)
Может, сделать метод `const`? Он же не меняет состояние объекта?

2021-10-26 07:01 UTC, KraPete commented on src/knxconverter.h
> +        static std::string KnxSourceAddressToString(const TTelegram& telegram);
Зачем нужны private static функции? Почему их нельзя положить в анонимное пространство имён в cpp?

2021-10-26 10:04 UTC, rkochkin commented on debian/wb-mqtt-knx.init
>  #!/bin/sh
Старый код. Пока не стал трогать. Только поправил. Нужно будет обсудить что с ним делать.

2021-10-26 10:10 UTC, rkochkin commented on src/knxconverter.h
> +        static std::string KnxSourceAddressToString(const TTelegram& telegram);
Согласен, можно.

2021-10-26 16:25 UTC, rkochkin commented on src/knxconverter.h
> +        static std::string KnxSourceAddressToString(const TTelegram& telegram);
Сделал

2021-10-26 16:32 UTC, rkochkin commented on src/knxclientservice.cpp
> +        sleep(timeout);
Сделал обход

2021-10-26 16:32 UTC, rkochkin commented on src/knxclientservice.cpp
> +            if (res == -1)
Сделал возвращаемые значения

2021-10-26 16:33 UTC, rkochkin commented on src/knxclientservice.cpp
> +    constexpr auto CLIENT_RECONNECT_PERIOD_S = 30;
Сделал

2021-10-27 05:52 UTC, KraPete commented on src/knxclientservice.cpp
> +                    usleep(std::chrono::duration_cast<std::chrono::microseconds>(IN_CONNECTION_REQUEST_TICK).count());
Сейчас модно [так](https://en.cppreference.com/w/cpp/thread/sleep_forl). И нет ада с кастами

2021-10-27 05:52 UTC, KraPete commented on src/knxconverter.h
> +        static std::string KnxTelegramToMqtt(const TTelegram& telegram);
Привет, Java! Зачем публичные статические методы, которые никак не влияют на поведение объектов класса?

2021-10-27 07:35 UTC, webconn commented on src/knxconverter.cpp
> +    if (std::get<0>(apciConvertResult)) {
Если этот tuple дальше используется с распаковкой индексами, то мне не нравится.

Проблема tuple в том, что приходится читать много кода, ведь у полей нет адекватных имён. Если не знать предметную область, можно придумать много трактовок этому bool: неправильный формат строки, не получилось что-то где-то загрузить, а может это флаг какой-то, мало ли.

Как минимум стоит распаковывать это с помощью `std::tie`, так можно хоть на месте добавить смысла с помощью имён. Можно ещё вернуть значение по указателю (мы ведь из контейнера его берём?), тогда это будет nullable и тоже удобно. В идеале это юзкейс для `optional`, но нам его ещё не завезли.

@KraPete что скажешь?

2021-10-27 07:48 UTC, rkochkin commented on src/knxconverter.h
> +        static std::string KnxTelegramToMqtt(const TTelegram& telegram);
Логическая группировка. Можно, конечно, занести под namespace converter{}. Мне кажется это эквивалентно будет.

2021-10-27 08:14 UTC, KraPete commented on src/knxconverter.cpp
> +    if (std::get<0>(apciConvertResult)) {
Я уже писал выше. Думаю, структура лучше.

2021-10-27 08:17 UTC, KraPete commented on src/knxconverter.h
> +        static std::string KnxTelegramToMqtt(const TTelegram& telegram);
Я за `namespace`

2021-10-27 12:14 UTC, rkochkin commented on src/knxclientservice.cpp
> +                    usleep(std::chrono::duration_cast<std::chrono::microseconds>(IN_CONNECTION_REQUEST_TICK).count());
Сделал по моде)

2021-10-27 12:14 UTC, rkochkin commented on src/knxconverter.h
> +        static std::string KnxTelegramToMqtt(const TTelegram& telegram);
Сделал

2021-10-27 12:17 UTC, rkochkin commented on src/knxconverter.cpp
> +    if (std::get<0>(apciConvertResult)) {
Оставил std::tie(). Функция приватная и небольшая. Не хотел бы для неё плодить лишние сущности.

2021-10-27 13:17 UTC, rkochkin commented on debian/wb-mqtt-knx.init
>  #!/bin/sh
Перенёс на systemd. @KraPete посмотри, пожалуйста.

2021-10-27 14:49 UTC, KraPete commented on debian/wb-mqtt-knx.service
> +Wants=wb-hwconf-manager.service wb-modules.service
Зачем это всё? Оно реально нужно?

2021-10-27 14:49 UTC, KraPete commented on debian/wb-mqtt-knx.service
> +After=network.target wb-hwconf-manager.service wb-modules.service
Вроде достаточно только
After=mosquitto.target

2021-10-27 15:26 UTC, webconn commented on debian/wb-mqtt-knx.service
> +Wants=wb-hwconf-manager.service wb-modules.service
hwconf скорее нужен, я считаю

2021-10-27 15:28 UTC, rkochkin commented on debian/wb-mqtt-knx.service
> +After=network.target wb-hwconf-manager.service wb-modules.service
Почистил. Проверил.

2021-10-27 15:29 UTC, rkochkin commented on debian/wb-mqtt-knx.service
> +Wants=wb-hwconf-manager.service wb-modules.service
Я уже убрал) Как понимаю он понадобится, когда конфиги добавятся в сервис. Но это будет в следующем PR.

2021-10-27 15:31 UTC, webconn commented on debian/wb-mqtt-knx.service
> +Wants=wb-hwconf-manager.service wb-modules.service
Не, просто после его загрузки мы можем расчитывать на то, что knx-модуль появился в системе. Впрочем, здесь это критично скорее для knxd, чем для wb-mqtt-knx.

Кстати, там всё в порядке будет, если knxd запустится позже, чем wb-mqtt-knx?

2021-10-27 16:54 UTC, rkochkin commented on debian/wb-mqtt-knx.service
> +Wants=wb-hwconf-manager.service wb-modules.service
Не очень. Ругнётся в лог и будет ждать таймаута до переподключения.
Поправил.

2021-10-28 05:40 UTC, KraPete commented on debian/wb-mqtt-knx.service
> +After=network.target wb-hwconf-manager.service wb-modules.service
Москиту, может, оставить?

2021-10-28 07:37 UTC, rkochkin commented
> 1. Надо комментарии к методам, не всегда ясно, что они делают, что им передавать, могут ли они выкидывать исключения, потокобезопасны ли они.

Планирую сделать в следующих PR. Добавил в Issue

> 2. Меня уже тут били по рукам за `std::tuple`. Лучше возвращать структуру с нормальными именами полей.

Обсудили. Оставил как есть. Функция приватная и маленькая, что-бы делать для неё структуру.

> 3. Стоит посмотреть, где можно добавить к методам const.

Добавил, вроде, везде.

> 4. Не понял, зачем сделаны интерфейсы `IKnxClient` и `IKnxService`?

Удалил IKnxService как излишний. IKnxClient нужен для уменьшения связности и для возможности юнит  тестирования. IKnxClient предоставляет высокоуровневый интерфейс для обмена пакетами с сетью KNX.

2021-10-28 10:15 UTC, KraPete reviewed
Не нашёл, где есть наследование от IKnxClient.

2021-10-28 10:15 UTC, KraPete commented on src/knxclientservice.cpp
> +        : KnxServerUrl{std::move(knxServerUrl)},
В чём преимущество такой схемы перед `const std::string&` ?

2021-10-28 10:15 UTC, KraPete commented on src/knxclientservice.h
> +            {
А можно реализацию не тащить в заголовочный файл? Это ко всем методам относится.

2021-10-28 10:15 UTC, KraPete commented on src/knxtelegram.cpp
> +std::vector<uint8_t> TTelegram::GetAPDUPayload() const
Здесь точно нужно копию возвращать?

2021-10-28 10:22 UTC, KraPete commented on src/knxclientservice.h
> +            {
Вероятно, весь класс вообще не нужен тут. Он же только в `cpp` используется?

2021-10-28 11:35 UTC, webconn commented on src/knxconverter.cpp
> +        } catch (std::exception& e) {
Если не лень, напиши сюда комментарий, что тут пусто, потому что дальше будет брошено исключение через `wb_throw`

2021-10-28 11:35 UTC, webconn commented on src/knxclientservice.cpp
> +            while (IsStarted) {
Я бы содержимое этого цикла выложил в отдельный метод, а то получилась очень длинная сложная конструкция с большим уровнем вложенности

2021-10-28 11:35 UTC, webconn commented on src/knxclientservice.cpp
> +        while (IsStarted) {
`IsStartedMutex` проверяется везде, но почему-то не здесь. Наверное, стоит перетащить эту проверку в метод-геттер, а ещё использовать `atomic`, если мы тут только `bool` пытаемся защитить

2021-10-28 11:35 UTC, webconn commented on src/knxclientservice.cpp
> +                if (OnReceiveTelegramHandler)
Аналогично, завёрнуто в мьютекс только в одном месте

2021-10-29 09:25 UTC, rkochkin commented on src/knxclientservice.cpp
> +        : KnxServerUrl{std::move(knxServerUrl)},
- Если в конструктор передаётся rvalue, то содержимое перемещается сначала в knxServerUrl переменную, а затем перемещается в приватный член класса KnxServerUrl. Два перемещения vs одно копирование.
- Запись короче:)

Например:

> std::string first{"abc"}, last{"def"};
> person p1{first, last};  // (1) копирование обеих строк
> person p2{std::move(first), last}; // !!! копирование только второй
> person p2{std::move(first), std::move(last)}; // (3) нет копирования
> person p3{"x", "y"}; // нет копирования

2021-10-29 10:07 UTC, KraPete commented on src/knxclientservice.cpp
> +        : KnxServerUrl{std::move(knxServerUrl)},
Это я понимаю, но у тебя везде вызывется с lvalue и наоборот добавляет лишнее копирование.

< discussion mode >
1. Конкретно в этом месте это странная оптимизация, т.к. реально вызов конструктора единичный при старте программы. Никто не оценит, а синтаксис спорный.

2. Я думаю, что если хочется оптимизировать rvalue, то стоит делать 2 конструктора.

< /discussion mode >

2021-10-29 12:10 UTC, rkochkin commented on src/knxclientservice.cpp
> +        : KnxServerUrl{std::move(knxServerUrl)},
Добавляет лишнее копирование или перемещение?
Lvalue вроде копируется и перемещается, вместо простого копирования. 
Ок, верну к константной ссылке.

2021-10-29 12:19 UTC, rkochkin commented on src/knxclientservice.cpp
> +            while (IsStarted) {
Согласен. Поправил.

2021-10-29 12:20 UTC, rkochkin commented on src/knxconverter.cpp
> +        } catch (std::exception& e) {
Сделал чуть больше кода, но почеловечнее.

2021-10-29 12:21 UTC, rkochkin commented on src/knxclientservice.h
> +            {
Да, убрал из KnxClientService

2021-10-29 12:31 UTC, webconn commented on src/knxclientservice.cpp
> +        while (IsStarted) {
Не нравится, что этот метод сам по себе запускается в таком же цикле (в `ReceiveLoop` уже есть `while (IsStarted)`. И всё ещё нет мьютекса/atomic

2021-10-29 12:45 UTC, KraPete commented on src/knxclientservice.cpp
> +        : KnxServerUrl{std::move(knxServerUrl)},
Да, ты прав. Не трогай ничего :)

2021-10-29 12:51 UTC, rkochkin commented on src/knxtelegram.cpp
> +std::vector<uint8_t> TTelegram::GetAPDUPayload() const
Как смог сделал без копии

2021-10-29 13:20 UTC, rkochkin commented on src/knxclientservice.cpp
> +                if (OnReceiveTelegramHandler)
Сделал геттер и сеттер

2021-10-29 13:39 UTC, rkochkin commented on src/knxclientservice.cpp
> +        while (IsStarted) {
Я пока не понимаю как развернуть эти два цикла - глаза замылились.
Один это подключение к knxd серверу, второй собственно приём. Если соединение рвётся, происходит переподключение.

2021-11-01 08:59 UTC, webconn commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Похоже, мьютекс теперь не нужен?

2021-11-01 08:59 UTC, webconn commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
Для чего здесь нужен mutable?

2021-11-01 08:59 UTC, webconn commented on src/knxclientservice.cpp
> +        while (IsStarted) {
Пометь тогда комментариями, какой цикл делает подключение, а в каком вертится логика, а то я могу представить ситуацию, в которой изменение заедет не в тот цикл и никто не заметит

2021-11-01 08:59 UTC, webconn commented on src/knxclientservice.cpp
> +        while (IsStarted) {
IsStarted стало atomic, теперь ок

2021-11-01 09:07 UTC, rkochkin commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
* SetterMutex вызывается в константном методе 
` void TKnxClientService::OnReceive(const TTelegram& telegram) const; `
* Вспомогательный объект

При желании можно убрать const и mutable.

2021-11-01 09:09 UTC, webconn commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
Мне кажется, `OnReceive` слишком странно делать `const`, это же callback, а не getter

2021-11-01 09:15 UTC, rkochkin commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Там есть логика:
```    
void TKnxClientService::Start()
    {
        {
            std::lock_guard<std::mutex> lg(IsStartedMutex);
            if (IsStarted) {
                wb_throw(knx::TKnxException, "Attempt to start already started driver");
            }
            IsStarted = true;
        }
 ```
Два неразрывных действия. Либо чтение и выброс исключения, либо чтение и запись. Возможно как-то можно это элегантнее сделать.

2021-11-01 09:26 UTC, webconn commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Так дело в том, что ты защищаешься так только от одновременного вызова `Start()`. Это реалистичный сценарий?

2021-11-01 09:37 UTC, rkochkin commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
Концептуально, по мне, он не меняет данные класса, а только вызывает константный метод объекта  `operator() const`.  
Например, настроенный статический анализатор сонар куба в этом месте ругнулся бы.

2021-11-01 09:39 UTC, webconn commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
@KraPete сделай нам консенсус в этом вопросе :)

2021-11-01 09:39 UTC, rkochkin commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
Хотя нет, не ругнулся. У нас бы не было mutable)
Уберу, сделаю как привычнее.

2021-11-01 09:45 UTC, rkochkin commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Я подсмотрел в коде из других репозиториев)
В принципе нет, не реалистичный. Start() Stop() вызываюся только в main().

2021-11-01 10:00 UTC, rkochkin commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
@webconn Убрать, и оставить только присваивание IsStarted = true?

2021-11-01 10:07 UTC, rkochkin commented on src/knxclientservice.cpp
> +        while (IsStarted) {
Пометил

2021-11-01 10:08 UTC, webconn commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Ну да

2021-11-01 10:09 UTC, KraPete commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
В `main`, но в разных потоках. Вероятность минимальная, но можно получить сюрприз. Или при рефакторинге выстрелить в ногу. У `atomic` есть `exchange`, который поможет сделать всё потокобезопасно в этом месте, хотя лично мне и мьютекс глаза не мозолил.

2021-11-01 10:13 UTC, webconn commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Вероятность вызвать одновременно Start и Stop, ты имеешь в виду? Ну как-то звучит крайне нереалистично. Если и оставлять мьютекс, то его надо переименовать, чтобы он ассоциировался не с флагом запущенности, а с процедурой запуска/остановки, в цикле мы ведь его не трогаем

2021-11-01 10:16 UTC, KraPete commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
Вроде бы это нормальная практика https://herbsutter.com/2013/01/01/video-you-dont-know-const-and-mutable/
@webconn `OnReceive` тут внутренняя логика, почему бы ему не быть `const`?

2021-11-01 10:19 UTC, KraPete commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Ну тогда `std::atomic` и `exchange` и `load`. Будет быстро, без мьютекса и потокобезопасно.

2021-11-01 10:19 UTC, webconn commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
Я считаю, что в общем случае callback-у странно быть `const`, потому что его задача - принять внешнее воздействие на объект

2021-11-01 11:07 UTC, rkochkin commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Я избавился от мьютекса IsStarted. 
@KraPete посмотри, пожалуйста.

2021-11-01 11:08 UTC, rkochkin commented on src/knxclientservice.h
> +        mutable std::mutex SetterMutex;
Убрал const и mutable

2021-11-01 11:13 UTC, webconn commented on src/knxtelegram.h
> +#define WB_MQTT_KNX_KNXTELEGRAM_H
Только обратил на это внимание. В 2к21 в этом месте можно использовать `#pragma once` :)

2021-11-01 11:22 UTC, rkochkin commented on src/knxtelegram.h
> +#define WB_MQTT_KNX_KNXTELEGRAM_H
Если бы это было стандартом, и не зависело от реализации компилятора, ставил бы везде `#pragma once` без сомнений.
Считаю это нужно добавить в соглашения по коду. Что мы соглашаемся везде использовать `#pragma once`

2021-11-01 11:23 UTC, rkochkin commented on src/knxtelegram.h
> +#define WB_MQTT_KNX_KNXTELEGRAM_H
@webconn  переделать хедеры на `#pragma once`?

2021-11-01 11:23 UTC, webconn commented on src/knxtelegram.h
> +#define WB_MQTT_KNX_KNXTELEGRAM_H
У нас это уже используется в serial как минимум. Думаю, надо вносить в codestyle. @KraPete?

2021-11-01 11:40 UTC, KraPete commented on src/knxtelegram.h
> +#define WB_MQTT_KNX_KNXTELEGRAM_H
Давайте внесём. Предлагаю, не заставлять всё переделывать, но в новых файлах пользоваться. Думаю, мы не столкнёмся с компиляторами, которые это не умеют.

2021-11-01 11:41 UTC, webconn commented on src/knxtelegram.h
> +#define WB_MQTT_KNX_KNXTELEGRAM_H
Ну в этом PR можно здесь переделать, я считаю, это же делается автозаменой

2021-11-01 11:42 UTC, webconn approved these changes
Осталось только поменять guard-ы на `#pragma once`, в остальном надо вливать, я считаю

2021-11-01 11:47 UTC, KraPete commented on src/knxclientservice.h
> +        std::mutex IsStartedMutex;
Я б только `exchange` использовал, но так тоже норм.

2021-11-01 13:22 UTC, rkochkin commented on src/knxtelegram.h
> +#define WB_MQTT_KNX_KNXTELEGRAM_H
Сделал

2021-11-01 14:35 UTC, KraPete approved these changes

2021-11-01 15:44 UTC, merged