Feature/40324 create group objects and configs
contactless/wb-mqtt-knx pull request #8
Opened 2021-11-18 17:54 UTC by rkochkin

Добавлено:
* Создание девайсов содержащих групповые объекты 
* Настройка контролов в зависимоти  типа KNX Data Point группового объекта
* Отправка и приём сообщений в mqtt и knx, разложенных по групповым адресам
* В настройке групповых объектов появился чекбокс "ReadOnly"

Сейчас поддерживаются только 4 типа Dpt:
* Raw_Value
* 1.xxx_B1
* 2.xxx_B2
* 9.xxx_2-Octet_Float_Value

2021-11-19 04:55 UTC, KraPete requested changes

2021-11-19 04:55 UTC, KraPete commented on src/configurator.cpp
> +        return {0, 0, 0};
Зачем? Это же никогда не выполнится

2021-11-19 04:55 UTC, KraPete commented on src/configurator.cpp
> +    knx::TKnxGroupAddress StringToGroupAddress(const std::string& str)
Вообще я стараюсь делать так, чтобы схема по максимуму валидровала входные данные. Вроде же сделали регулярку, которая тут не пропускает пробелы, зачем их удалять? Опять же регулярка проверяет 2 или 3 группы. 
Короче, мы либо доверяем тому, что сюда пришло, т.к. оно прошло через валидатор, либо вообще ничему не доверяем и проверяем всё тут. Зачем двойную работу делать?

2021-11-19 04:55 UTC, KraPete commented on src/configurator.cpp
> +            return {static_cast<uint32_t>(std::stoi(tokens[0])),
1. Что будет, если я введу 011/022/033 ?
2. Зачем было резать пробелы вверху, если stoi на них и так не смотрит? Да ещё и валидатор должен их не пускать?

2021-11-19 04:55 UTC, KraPete commented on src/configurator.cpp
> +    ConfigRoot = std::make_unique<Json::Value>(WBMQTT::JSON::Parse(configPath));
Зачем указатель? У Json::Value есть move-конструктор.

2021-11-19 04:55 UTC, KraPete commented on src/configurator.cpp
> +    if (GroupObjectBuilder == nullptr) {
Стоит это в конструкторе проверять. И вообще, можно ли не указатель передавать, а IGroupObjectMqttBuilder&, кучу кода не надо будет писать?

2021-11-19 04:55 UTC, KraPete commented on src/configurator.h
> +    class TConfigurator
Я дальше код не смотрел, но зачем нам это в виде класса? Одной функции с 4 параметрами не хватит?

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/dpt9.cpp
> +// TODO Need check negative numbers
Может, сразу это сделать?

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +                                               .SetOrder(0)
Почему 0?

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +                                               .SetError("")
Это можно не писать

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +        auto isValid = Dpt->FromMqtt(index, value);
```cpp
if (!Dpt->FromMqtt(index, value)) {
    return;
}
data = Dpt->ToKnx();
```

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +                return;
И тут

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +            auto tx = control->GetDevice()->GetDriver()->BeginTx();
Открывать транзакцию - очень дорого, лучше открыть её один раз и сделать кучу SetValue, чем открывать по одной на каждое SetValue

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqttbuilder.cpp
> +    if (parameter.Type == "Raw_Value") {
В глазах рябит. Можно это сделать ассоциативным массивом?

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqttbuilder.cpp
> +        MqttDeviceDriver->BeginTx()->RemoveDeviceById(device->GetId());
Опять, лучше одну транзакцию, чем кучу

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobjectcontroller.cpp
> +    if (groupObject) {
Я честно не понимаю кода с ветвлением, у которого в каждой ветке return. :(

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobjectcontroller.cpp
> +    if (GroupObjectList.erase(address)) {
return GroupObjectList.erase(address); ?

2021-11-19 04:55 UTC, KraPete commented on src/knxlegacydevice.cpp
> +            } catch (const TKnxException& e) {
TKnxException же от std::exception отнаследован

2021-11-19 04:55 UTC, KraPete commented on src/knxlegacydevice.cpp
> +    } catch (const std::exception& e) {
И тут

2021-11-19 04:55 UTC, KraPete commented on test/config/wb-mqtt-knx_bad.conf
> +{
Можно комментарий, что здесь "bad" ?

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +    std::vector<uint8_t> data;
При появлении исключения тут, мы скорее всего положим весь сервис. Может просто в лог ругнуться?

2021-11-19 04:55 UTC, KraPete commented on src/knxgroupobject/idpt.h
> +            double min;
С заглавной

2021-11-19 07:18 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +    std::vector<uint8_t> data;
Согласен, добавлю.
Сейчас метод, вызывающий обработчик эвента в mqtt драйвере, ловит эти исключения, и ругается в лог. Сервис не падает. Проверил.

2021-11-19 07:31 UTC, rkochkin commented on src/configurator.cpp
> +            return {static_cast<uint32_t>(std::stoi(tokens[0])),
Валидатор схемы пропускает пробелы, но режет нули.  Обсуждали это с @webconn в прошлый раз.
011/022/033 ввести не получится в веб форме.
Уберу дополнительную обрезку пробелов до stoi()

2021-11-19 08:34 UTC, rkochkin commented on src/knxgroupobject/idpt.h
> +            double min;
Поправил

2021-11-19 08:34 UTC, rkochkin commented on test/config/wb-mqtt-knx_bad.conf
> +{
Указал

2021-11-19 08:34 UTC, rkochkin commented on src/knxgroupobjectcontroller.cpp
> +    if (groupObject) {
Поправил

2021-11-19 08:34 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +        auto isValid = Dpt->FromMqtt(index, value);
Поправил

2021-11-19 08:34 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +                return;
Поправил

2021-11-19 08:35 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +                                               .SetError("")
Сделал

2021-11-19 08:35 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +                                               .SetOrder(0)
Убрал

2021-11-19 08:35 UTC, rkochkin commented on src/configurator.cpp
> +        return {0, 0, 0};
Убрал

2021-11-19 08:52 UTC, rkochkin commented on src/knxlegacydevice.cpp
> +    } catch (const std::exception& e) {
Убрал производный

2021-11-19 08:52 UTC, rkochkin commented on src/knxlegacydevice.cpp
> +            } catch (const TKnxException& e) {
Убрал производный

2021-11-19 08:52 UTC, rkochkin commented on src/knxgroupobject/mqttbuilder.cpp
> +        MqttDeviceDriver->BeginTx()->RemoveDeviceById(device->GetId());
Поправил

2021-11-19 08:52 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +            auto tx = control->GetDevice()->GetDriver()->BeginTx();
Поправил

2021-11-19 13:43 UTC, rkochkin commented on src/knxgroupobject/mqttbuilder.cpp
> +    if (parameter.Type == "Raw_Value") {
Сделал

2021-11-19 13:43 UTC, rkochkin commented on src/knxgroupobjectcontroller.cpp
> +    if (GroupObjectList.erase(address)) {
Поправил

2021-11-19 13:43 UTC, rkochkin commented on src/knxgroupobject/dpt9.cpp
> +// TODO Need check negative numbers
Проверил отрицательные значения

2021-11-19 14:36 UTC, rkochkin commented on src/configurator.cpp
> +    ConfigRoot = std::make_unique<Json::Value>(WBMQTT::JSON::Parse(configPath));
Заменил

2021-11-19 14:36 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +    std::vector<uint8_t> data;
Добавил обработку исключения здесь

2021-11-19 16:04 UTC, rkochkin commented on src/configurator.h
> +    class TConfigurator
Предполагалась ещё настройка knx клиента. Пока её не будет.
Оформил функцией.

2021-11-19 16:04 UTC, rkochkin commented on src/configurator.cpp
> +    if (GroupObjectBuilder == nullptr) {
Переделал.

2021-11-19 16:12 UTC, rkochkin commented on src/configurator.cpp
> +    knx::TKnxGroupAddress StringToGroupAddress(const std::string& str)
Из функции всё равно нужно что-то вернуть или сгенерить исключение. 
И всё равно есть ветвление в зависимости от длины адреса.  
Мне кажется что лучше читается функция, в которой видно, что она ожидает.
Лишнюю проверку я убрал

2021-11-21 07:32 UTC, KraPete commented on src/configurator.cpp
> +    knx::TKnxGroupAddress StringToGroupAddress(const std::string& str)
Я писал про дублирование проверок в схеме и тут. Чтоб не было так, что оно размазано: половина в схеме, половина - тут, ещё и часть пересекается.

2021-11-22 14:36 UTC, KraPete requested changes
Я бы прошёлся по всем классам с виртуальными методами и сделал им виртуальные деструкторы, чтоб потом не собирать грабли.

2021-11-22 14:36 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +                           ->CreateControl(MqttLocalDevice->GetDriver()->BeginTx(),
Всё ещё создаётся транзакция на каждый чих.

2021-11-22 14:36 UTC, KraPete commented on src/knxgroupobject/mqtt.cpp
> +            ErrorLogger.Log() << exception.what();
Можно более внятные сообщения выдавать, с указанием контрола или группового объекта, чтоб можно было понять, где сломалось. А то будет куча сообщений, что не смогли получить число из строки и т.п., а как лечить и где искать - хз.

2021-11-22 14:36 UTC, KraPete commented on src/knxgroupobject/mqttbuilder.cpp
> +    tx->End();
Можно End не вызывать, оно в деструкторе вызовется

2021-11-23 08:46 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +                           ->CreateControl(MqttLocalDevice->GetDriver()->BeginTx(),
Проглядел похоже. Поправил.

2021-11-23 08:46 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +            ErrorLogger.Log() << exception.what();
Добавил

2021-11-23 08:58 UTC, KraPete approved these changes

2021-11-23 09:45 UTC, webconn requested changes

2021-11-23 09:45 UTC, webconn commented on src/configurator.cpp
> +    auto devices = (configRoot)["devices"];
Тут нужны скобки?

2021-11-23 09:45 UTC, webconn commented on src/configurator.cpp
> +        auto deviceNameStr = device["deviceTitle"].asString();
Конкретно здесь не принципиально, но я предлагаю взять за правило не пользоваться словом `name`. `id` для программ, `title` для людей

2021-11-23 09:45 UTC, webconn commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
Мы обычно определяем типы вроде `PTypeName` как `std::shared_ptr<TTypeName>`, чтобы не писать длинные определения. Можно и тут это сделать везде

2021-11-23 09:45 UTC, webconn commented on src/knxclientservice.h
> +        void Send(const TTelegram& telegram) const override;
Нам `const` у метода тут зачем-то нужен? Это же нас ограничивает на ровном месте с непонятной выгодой

2021-11-23 09:45 UTC, webconn commented on src/knxgroupaddress.h
> +        TKnxGroupAddress(uint32_t main, uint32_t sub);
`StringToGroupAddress` стоило бы сюда положить, например, в виде статического метода `TKnxGroupAddress::FromString`, а то однажды он понадобится, но его не найдут. К тому же конвертор из типа в строку уже тут.

2021-11-23 09:45 UTC, webconn commented on src/knxgroupobject/idpt.h
> +            std::string Name;
Думаю, тут лучше `id`

2021-11-23 09:45 UTC, webconn commented on src/knxgroupobject/dpt1.h
> +#pragma once
Где-нибудь в этих файлах хотелось бы в комментариях какое-нибудь описание, что за тип данных тут разбирается, чтобы при редактировании не пришлось одновременно открывать спеки

2021-11-23 09:45 UTC, webconn commented on src/knxgroupobject/dpt1.cpp
> +    return false;
А тут не лучше было бы исключение бросать? Сейчас мы просто проглатываем ошибку

2021-11-23 09:45 UTC, webconn commented on src/knxgroupobject/mqtt.cpp
> +                                   const std::string& controlName,
`title`

2021-11-23 09:45 UTC, webconn commented on src/knxgroupobject/mqtt.cpp
> +            control->SetValue(tx, std::move(mqttData.at(index))).Wait();
Тут можно было бы `Wait()` перенести в отдельный цикл, чуть лучше будет отзывчивость у сервиса. Но это не обязательно переделывать сейчас

2021-11-23 09:45 UTC, webconn commented on src/knxgroupobject/mqttbuilder.cpp
> +void TGroupObjectMqttBuilder::RemoveUnusedControls()
Можно чуть подробней о том, что в этом методе происходит? Почему только у последнего девайса в списке?

2021-11-23 10:45 UTC, rkochkin commented on src/configurator.cpp
> +    auto devices = (configRoot)["devices"];
Уже нет. Поправил.

2021-11-23 10:45 UTC, rkochkin commented on src/configurator.cpp
> +        auto deviceNameStr = device["deviceTitle"].asString();
Поправил

2021-11-23 10:45 UTC, rkochkin commented on src/knxgroupobject/idpt.h
> +            std::string Name;
Поправил

2021-11-23 10:45 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +                                   const std::string& controlName,
Поправил

2021-11-23 11:29 UTC, rkochkin commented on src/knxclientservice.h
> +        void Send(const TTelegram& telegram) const override;
Константный метод не ограничивает, а расширяет сферу использования.

Преимущество  в том, что метод доступен для вызова, например, по константной ссылке на класс. 
Это важно когда объект одного класса  использует объект второго класса с запретом на модификацию этого  второго класса.
Модификация данных класса может быть как явная, через интерфейс класса(сеттеры например), так и скрытая.
Скрытая - это модификация данных класса при вызове, например, того же `send()`, который казалось-бы не должен ничего модифицировать.
Это возможно  так-же и при ошибках и недоработках в реализации метода, от которых никто не застрахован.

К чему это может привести: добавит головняк при многопоточном использовании, да и в однопоточном может.
При использовании константных методов константного объекта класса хотя бы есть гарантия, что его не повредишь при использовании.

2021-11-23 11:38 UTC, rkochkin commented on src/knxclientservice.h
> +        void Send(const TTelegram& telegram) const override;
Здесь уберу const: в коде не использую константные ссылки на объекты класса с интерфейсом `Send()`, так что не принципиально пока.

Но ещё раз повторюсь: даже если аккуратно писать код, и умозрительно его проверять, ошибки всё равно будут. Чем аккуратней тем более не очевидные:)

Лучше сразу ограничить возможность возникновения ошибки, чем тратить время и деньги на их поиск.

2021-11-23 11:47 UTC, webconn commented on src/knxclientservice.h
> +        void Send(const TTelegram& telegram) const override;
Я согласен с тем, что чем больше в коде `const`, тем лучше (в общем случае). Но мне непонятно, почему `Send()` должен быть `const`: по логике, он может поменять состояние класса (где-то могут обновиться счётчики, где-то добавиться дескрипторы посылки, что-то такое). Если потом понадобится делать подобные штуки, придётся либо переделывать определение `Send`, либо добавлять внутрь класса `mutable`, что некрасиво.

2021-11-23 12:32 UTC, rkochkin commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
Предлагаю оставить как есть.

Плюсы: 
* Скорость чтения кода. Для того, что-бы понять, что представляет из себя аргумент нужно зайти в одноимённый хедер интерфейса. Это только один шаг поиска. 
`std::shared_ptr<>` тривиальный элемент не замусоливающий зрение при таком его использовании.
* Очевидность. Всё на поверхности.

Минусы:
* Много букав в сигнатуре функции

Использование PTypeName:

Плюсы:
* Короткая запись

Минусы:

* Неочевидность. Необходимо хранить в голове уже два типа PTypeName и TTypeName. Это уже две сущности. Хотя одна из них, по сути, тривиальна. 
Необходимо всегда держать правило перевода в голове, что при изменении синатуры функции, например указателя PTypeName, на ссылку, нужно поменять его на TTypeName. 

* Меньше скорость чтения. Чтобы найти требуемый класс нужно сделать два поиска. Либо в голове конвертить PTypeName в TTypeName, что не всегда быстро.

В этом проекте я не создаю общие библиотечные методы и классы. Добавление дополнительного псевдонима только увеличит количество кода (количество ошибок), не приведя к очевидным для меня плюсам.

Псевдоним оправдан когда в него добавляется не тривиальный. смысл.
Например: `using Speed = uint8_t;`
Это позволяет абстрагироваться от реального типа и легко модифицировать используемый тип, если, ,например, потребуется большая разрядность, или создание класса.

P. S. Это лишь мое предложение. Естественно могу переделать на PTypeName

2021-11-23 12:44 UTC, rkochkin commented on src/knxclientservice.h
> +        void Send(const TTelegram& telegram) const override;
Счетчики в `mutable`, на мой взгляд, нормальное решение. Это служебные вещи, которые не должны торчать во внешний мир.
`mutable` явно предупреждает, что эти данные изменяются, а все остальные нет. Естественно если `mutable` понатыкан везде в данных класса это явно говорит плохом проектировании класса.

А вот когда нет ни модификаторов методов const, ни const в данных класса это вообще ни о чём не говорит. Плохо написано или "это всё так и должно быть"  не ясно.

2021-11-23 12:52 UTC, webconn commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
Сильный аргумент "за" - мы такую нотацию используем везде и давно. `PTypeName` в `TTypeName` преобразуется довольно быстро в голове.

Короткая запись полезна, потому что иногда начинаются истории вроде вектора с указателями, и тогда определения становятся длинными и плохочиаемыми (`std::vector<std::shared_ptr<WBMQTT::TControl>>`)

2021-11-23 13:04 UTC, rkochkin commented on src/knxgroupobject/mqttbuilder.cpp
> +void TGroupObjectMqttBuilder::RemoveUnusedControls()
Тут небольшая печаль c дизайном. 
Для того чтобы не выносить PLocalDevice наружу за пределы TGroupObjectMqttBuilder пришлось сделать зависимость класса от состояний. 
Сначала создаешь устройство `LinkDevice()`, создаёшь групповые объекты( с mqtt контролами ) `Create()`, а после удаляешь неиспользуемые конролы у этого устройства `RemoveUnusedControls()`.

Уже один раз переделывал, чтобы упростить.

2021-11-23 13:07 UTC, rkochkin commented on src/knxgroupaddress.h
> +        TKnxGroupAddress(uint32_t main, uint32_t sub);
Согласен

2021-11-23 13:10 UTC, rkochkin commented on src/knxgroupobject/dpt1.h
> +#pragma once
Да, добавлю. 
Если я добавлю Doxyfile  в проект - это нормально будет?

2021-11-23 13:35 UTC, webconn commented on src/knxgroupobject/dpt1.h
> +#pragma once
Добавь, если не лень

2021-11-23 13:42 UTC, webconn commented on src/knxclientservice.h
> +        void Send(const TTelegram& telegram) const override;
Я вижу это так:
 - если ты делаешь контейнер для данных, то надо везде, где нужно, проставить `const`;
 - если ты реализуешь взаимодействие с чем-то внешним, нет особого смысла делать `const` в каждом методе (но стоит сделать для геттеров и каких-нибудь действительно неизменных параметров);
 - во всяких управляющих классах (фабриках, реализациях логики) в этом вообще особо нет смысла, кроме ну совсем очевидных моментов.
 
А на `mutable` у меня аллергия, для меня он выглядит как костыль :)

2021-11-23 15:12 UTC, rkochkin commented on src/knxgroupaddress.h
> +        TKnxGroupAddress(uint32_t main, uint32_t sub);
Сделал

2021-11-23 15:12 UTC, rkochkin commented on src/knxclientservice.h
> +        void Send(const TTelegram& telegram) const override;
Убрал const

2021-11-23 15:19 UTC, rkochkin commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
@webconn можно ограничиться интерфейсами? 
Кстати, для интерфейсов префикс " I "  теряется, когда превращается в указатель. 
И становится не понятно `PTypeName` - это интерфейс или реализация. 
С абстрактными базовыми то понятно, у них есть `Base` в названии.

2021-11-23 15:46 UTC, webconn commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
Не думаю, что при нашем количестве типов это такая большая проблема. Плюс, в любом нормальном редакторе перейти к реализации можно в два клика (даже у меня в vim это работает :) )

2021-11-23 15:47 UTC, webconn commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
@KraPete что думаешь по этому поводу?

2021-11-23 15:58 UTC, webconn commented on src/knxgroupobject/mqttbuilder.cpp
> +void TGroupObjectMqttBuilder::RemoveUnusedControls()
Всё равно не очень понятно. Это удаление контролов из MQTT с прошлого запуска?

2021-11-24 05:02 UTC, KraPete commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
1. Мне не нравятся Pxxx :) Фиг поймёшь, надо ли их разрушать самому, или оно развалится само. IDE и компилятор, кончено, помогут, но осадочек остаётся.
2. Мне не нравится бездумное использование `std::shared_ptr` везде вместо указателей и ссылок. Это накладные расходы на ровном месте для обеспечения потокобезопасности. Плюс в коде (во всех проектах) практически нет проверок на то, что оно может быть `nullptr`. Т.е. имеем указатель, а думаем, что ссылка. Третий момент - циклические ссылки, которе где-то героически разруливаются через `std::weak_ptr`, а где-то вообще их никто не видит. Единственный аргумент "за", с которым я согласен, у нас потом появятся начинающие разработчики, и они налажают с управлением памятью. Я считаю, что должна быть явная стратегия владения объектами.

2021-11-24 05:34 UTC, rkochkin commented on src/knxgroupobject/mqttbuilder.cpp
> +void TGroupObjectMqttBuilder::RemoveUnusedControls()
Да, это удаление контролов из прошлого запуска. Сделал по образцу из других модулей.

2021-11-24 08:17 UTC, webconn commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
1. А нам что-то вообще надо разрушать самим? `Pxxx` у нас был затеян как алиас для `shared_ptr` как раз чтобы не думать и сохранить короткую запись.
2. Ну да, согласен с тем, что `shared_ptr` несколько расслабляет. С другой стороны, он действительно ведёт себя как ссылка (вроде у нас нигде не происходит деинициализации этих указателей, и мы не создаём их пустыми). Циклические ссылки где-то наверняка возникают, но про них никто не знает до тех пор, пока не начинает активно течь память, а чинится это относительно легко.

Я призываю в это обсуждение @evgeny-boger и по результатам предлагаю решение записать в codestyle, чтобы к этому не возвращаться.

2021-11-24 08:28 UTC, rkochkin commented on src/knxgroupobject/dpt1.h
> +#pragma once
Добавил Doxyfile и сделал краткие описания реализованных датапоинтов.
Для генерации документации нужно в корне проекта `wb-mqtt-knx/` запустить `~#  doxygen`.
Генератор сложит html файлы в папку `doc/`

2021-11-24 08:54 UTC, webconn commented on src/knxgroupobject/dpt1.h
> +#pragma once
Отлично, спасибо! Допиши про `doxygen` в README ещё, пожалуйста

2021-11-24 09:07 UTC, rkochkin commented on src/knxgroupobject/dpt1.cpp
> +    return false;
Хотелось бы максимально уменьшить многословность в Dpt классах. Потому как их over 60.
Если сообщение не корректно, легче вернуть false, или true. Чем в каждом хранить практически одинаковые строки для what().
Мне не совсем понятно что ошибки не надо проглатывать, а ругаться в лог. Лог может быстро переполнится просто от неверного конфига. Хотя отзыв пользователю нужен, что не всё хорошо.

2021-11-24 09:29 UTC, rkochkin commented on src/knxgroupobject/dpt1.cpp
> +    return false;
Я думаю самое верное поведение при некорректных для этого датапоинта данных - отправка ошибки в MQTT топик /meta/error при помощи  TControl::SetError(). 
Если пользователь что-то не так настроил он может сразу увидеть ошибку во вкладке устройства.
Потому как некорректные для одного датапоинта данные могут быть корректны для другого. 
@webconn Как думаешь?

2021-11-24 09:44 UTC, webconn commented on src/knxgroupobject/dpt1.cpp
> +    return false;
Если ошибка в момент отправки в mqtt, то да, можно ставить `/meta/error`, хотя я не помню, делает ли так кто-то в нашей конвенции. По-моему, сейчас идёт ругань в лог.

Моя точка зрения насчёт исключений в dpt в том, что они позволяют получить дополнительную информацию о том, что именно не так, в отличии от возвращённого false.

2021-11-24 10:03 UTC, rkochkin commented on src/knxgroupobject/dpt1.cpp
> +    return false;
Так как делать тогда? Слать в лог или слать в /meta/error ?
Повторюсь, легко ошибиться в конфиге и указать не тот тип датапоинта и получить ошибку.
В serial реализована отправка в /meta/error

2021-11-24 10:05 UTC, webconn commented on src/knxgroupobject/dpt1.cpp
> +    return false;
Думаю, надо и то, и другое

2021-11-24 12:28 UTC, rkochkin commented on src/knxgroupobject/dpt1.cpp
> +    return false;
Сделал и то и другое и с исключениями.

2021-11-24 13:59 UTC, rkochkin commented on src/knxgroupobject/mqtt.cpp
> +            control->SetValue(tx, std::move(mqttData.at(index))).Wait();
Пока не буду трогать. Как правило Датапоинт состоит из одного поля, редко когда из двух и более.

2021-11-24 14:07 UTC, rkochkin commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
Сделал алиасы  `shared_ptr<>`

2021-11-25 04:14 UTC, KraPete commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
По моему, в 99% случаев `shared_ptr` вообще не нужен. Обычно надо `unique_ptr`. Он мне нравится тем, что нет накладных расходов, и в сигнатуре функции явно видно, чтопроисходит передача ответственности за время жизни объекта. Кстати, в этом конкретном месте тоже `shared_ptr` не нужен, а нужен `unique_ptr`. В сериале вот напихали `shared_ptr` везде, теперь использовать нормальные ссылки - боль, половину сигнатур функций переделывать. Я за разумное использование предоставляемых возможностей :) Вообще очень нехватает класса, который передаёт по значению объект, но предоставляет методы базового класса. Такой `unique_ptr`, но без возможности присвоить и инициализировать `nullptr`.

2021-11-25 10:47 UTC, webconn reviewed
Небольшая ремарка по стилю, в остальном думаю, что пора вливать

2021-11-25 10:47 UTC, webconn commented on src/knxgroupobject/dpt1.cpp
> +    } else
Надо добавить скобки вокруг тела `else` по нашему codestyle. Странно, что clang у нас это не проверяет

2021-11-25 10:51 UTC, webconn commented on src/iknxgroupobjectcontroller.h
> +                                    const std::shared_ptr<object::IGroupObject>& groupObject) = 0;
По поводу `unique_ptr` спорно, не всегда же нужно передавать владение, а `unique_ptr` by design не даст тебе сделать шаг в сторону. Хотя в отдельных местах это может быть полезно. Вообще я скорее за использование `weak_ptr` там, где возможно.

2021-11-25 11:09 UTC, KraPete commented on src/knxgroupobject/dpt1.cpp
> +    } else
clang-format же форматирует только, если надо что-то добавлять/убирать надо cppcheck/clang-tidy и т.п. использовать.

2021-11-25 11:48 UTC, webconn approved these changes

2021-11-25 12:20 UTC, merged